theme: minima

author:
  name: Simon Perche
  email: simon.perche@liris.cnrs.fr

description: >
  The project page of the paper Authoring Terrains with Spatialised Style published at Pacific Graphics 2023.
