title: Authoring Terrains with Spatialised Style

theme: minima

author:
  name: Simon Perche
  email: "simon.perche@liris.cnrs.fr"

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/simonperche/authoring_terrains_with_spatialised_stylel" }

description: >
  The project page of the paper Authoring Terrains with Spatialised Style published at Pacific Graphics 2023.
